/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_fernandopadilla;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wendy
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    ArrayList<Consola> consolas = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        popupM = new javax.swing.JPopupMenu();
        menuEditar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuEliminar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuListarJuegos = new javax.swing.JMenuItem();
        jd_modificarE = new javax.swing.JDialog();
        panel_aggC1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tf_id2 = new javax.swing.JTextField();
        tf_fabricante2 = new javax.swing.JTextField();
        tf_años2 = new javax.swing.JTextField();
        tf_precio2 = new javax.swing.JTextField();
        tf_modelo2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tf_numControles1 = new javax.swing.JTextField();
        tf_almacenamiento1 = new javax.swing.JTextField();
        tf_tipoC1 = new javax.swing.JTextField();
        btn_modC = new javax.swing.JButton();
        jd_ListarJuegos = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaJ = new javax.swing.JList<>();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tf_nombreJ = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_desc = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel36 = new javax.swing.JLabel();
        tf_precioJuego = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        rb_Nuevo = new javax.swing.JRadioButton();
        rb_usado = new javax.swing.JRadioButton();
        jLabel38 = new javax.swing.JLabel();
        rb_rentableSi = new javax.swing.JRadioButton();
        rb_rentableNo = new javax.swing.JRadioButton();
        jLabel39 = new javax.swing.JLabel();
        rb_aggSi = new javax.swing.JRadioButton();
        rb_aggNo = new javax.swing.JRadioButton();
        jLabel40 = new javax.swing.JLabel();
        tf_cantD = new javax.swing.JTextField();
        btn_aggJ = new javax.swing.JButton();
        jd_modificarP = new javax.swing.JDialog();
        panel_aggP1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tf_id3 = new javax.swing.JTextField();
        tf_fabricante3 = new javax.swing.JTextField();
        tf_años3 = new javax.swing.JTextField();
        tf_precio3 = new javax.swing.JTextField();
        tf_modelo3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rb_grande1 = new javax.swing.JRadioButton();
        rb_mediana1 = new javax.swing.JRadioButton();
        rb_small1 = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        tf_duracionB1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        rb_Si1 = new javax.swing.JRadioButton();
        rb_No1 = new javax.swing.JRadioButton();
        btn_modP = new javax.swing.JButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        popupM_Juegos = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panel_aggC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_fabricante = new javax.swing.JTextField();
        tf_años = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        tf_modelo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_numControles = new javax.swing.JTextField();
        tf_almacenamiento = new javax.swing.JTextField();
        tf_tipoC = new javax.swing.JTextField();
        btn_aggC = new javax.swing.JButton();
        panel_aggP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_id1 = new javax.swing.JTextField();
        tf_fabricante1 = new javax.swing.JTextField();
        tf_años1 = new javax.swing.JTextField();
        tf_precio1 = new javax.swing.JTextField();
        tf_modelo1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rb_grande = new javax.swing.JRadioButton();
        rb_mediana = new javax.swing.JRadioButton();
        rb_small = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        tf_duracionB = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        rb_Si = new javax.swing.JRadioButton();
        rb_No = new javax.swing.JRadioButton();
        btn_aggP = new javax.swing.JButton();
        panel_Listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_lista = new javax.swing.JTable();

        menuEditar.setText("Editar");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        popupM.add(menuEditar);
        popupM.add(jSeparator1);

        menuEliminar.setText("Eliminar");
        menuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEliminarActionPerformed(evt);
            }
        });
        popupM.add(menuEliminar);
        popupM.add(jSeparator2);

        menuListarJuegos.setText("Ver Juegos");
        menuListarJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarJuegosActionPerformed(evt);
            }
        });
        popupM.add(menuListarJuegos);

        panel_aggC1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel17.setText("Identificacion");

        jLabel18.setText("Fabricante");

        jLabel19.setText("Años de uso");

        jLabel20.setText("Precio");

        jLabel21.setText("Modelo");

        jLabel22.setText("Numero de Controles");

        jLabel23.setText("Almacenamiento");

        jLabel24.setText("Tipo de conexion");

        btn_modC.setText("Modificar");
        btn_modC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_aggC1Layout = new javax.swing.GroupLayout(panel_aggC1);
        panel_aggC1.setLayout(panel_aggC1Layout);
        panel_aggC1Layout.setHorizontalGroup(
            panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggC1Layout.createSequentialGroup()
                .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_aggC1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggC1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(41, 41, 41)
                                .addComponent(tf_modelo2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggC1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(tf_años2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggC1Layout.createSequentialGroup()
                                .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggC1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(tf_precio2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggC1Layout.createSequentialGroup()
                                        .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_id2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(tf_fabricante2))))
                                .addGap(0, 1, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_tipoC1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_almacenamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_numControles1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(panel_aggC1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_modC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        panel_aggC1Layout.setVerticalGroup(
            panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggC1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(tf_numControles1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_fabricante2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(tf_almacenamiento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tf_años2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(tf_tipoC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_precio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_modelo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btn_modC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_modificarELayout = new javax.swing.GroupLayout(jd_modificarE.getContentPane());
        jd_modificarE.getContentPane().setLayout(jd_modificarELayout);
        jd_modificarELayout.setHorizontalGroup(
            jd_modificarELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarELayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_aggC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jd_modificarELayout.setVerticalGroup(
            jd_modificarELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarELayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_aggC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        listaJ.setModel(new DefaultListModel());
        listaJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaJMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaJ);

        jLabel33.setText("Nombre");

        jLabel34.setText("Descripcion");

        ta_desc.setColumns(20);
        ta_desc.setRows(5);
        jScrollPane3.setViewportView(ta_desc);

        jLabel35.setText("Fecha de Lanzamiento");

        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        jLabel36.setText("Precio");

        jLabel37.setText("Estado");

        buttonGroup3.add(rb_Nuevo);
        rb_Nuevo.setText("Nuevo");

        buttonGroup3.add(rb_usado);
        rb_usado.setText("Usado");

        jLabel38.setText("Rentable");

        buttonGroup4.add(rb_rentableSi);
        rb_rentableSi.setText("Si");

        buttonGroup4.add(rb_rentableNo);
        rb_rentableNo.setText("No");

        jLabel39.setText("Agregado");

        buttonGroup5.add(rb_aggSi);
        rb_aggSi.setText("Si");

        buttonGroup5.add(rb_aggNo);
        rb_aggNo.setText("No");

        jLabel40.setText("Cant. Disponible");

        btn_aggJ.setText("Agregar");
        btn_aggJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aggJMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nombreJ))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(tf_precioJuego)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rb_Nuevo)
                                .addGap(18, 18, 18)
                                .addComponent(rb_usado))
                            .addComponent(jLabel38)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rb_rentableSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_rentableNo))
                            .addComponent(jLabel39)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rb_aggSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_aggNo))
                            .addComponent(jLabel40))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tf_cantD, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btn_aggJ, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(tf_nombreJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_precioJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_Nuevo)
                            .addComponent(rb_usado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_rentableSi)
                            .addComponent(rb_rentableNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_aggSi)
                            .addComponent(rb_aggNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_cantD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_aggJ, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jd_ListarJuegosLayout = new javax.swing.GroupLayout(jd_ListarJuegos.getContentPane());
        jd_ListarJuegos.getContentPane().setLayout(jd_ListarJuegosLayout);
        jd_ListarJuegosLayout.setHorizontalGroup(
            jd_ListarJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarJuegosLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_ListarJuegosLayout.setVerticalGroup(
            jd_ListarJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListarJuegosLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_aggP1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel25.setText("Identificacion");

        jLabel26.setText("Fabricante");

        jLabel27.setText("Años de uso");

        jLabel28.setText("Precio");

        jLabel29.setText("Modelo");

        jLabel30.setText("Tamaño Pantalla");

        buttonGroup1.add(rb_grande1);
        rb_grande1.setText("Grande");

        buttonGroup1.add(rb_mediana1);
        rb_mediana1.setText("Mediana");

        buttonGroup1.add(rb_small1);
        rb_small1.setText("Pequeña");

        jLabel31.setText("Duracion de Bateria");

        jLabel32.setText("Tiene Estuche");

        rb_Si1.setText("Si");

        rb_No1.setText("No");

        btn_modP.setText("Modificar");
        btn_modP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_aggP1Layout = new javax.swing.GroupLayout(panel_aggP1);
        panel_aggP1.setLayout(panel_aggP1Layout);
        panel_aggP1Layout.setHorizontalGroup(
            panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggP1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_aggP1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(41, 41, 41)
                        .addComponent(tf_modelo3))
                    .addGroup(panel_aggP1Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(tf_precio3))
                    .addGroup(panel_aggP1Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(tf_años3))
                    .addGroup(panel_aggP1Layout.createSequentialGroup()
                        .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_id3)
                            .addComponent(tf_fabricante3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_aggP1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_duracionB1))
                    .addGroup(panel_aggP1Layout.createSequentialGroup()
                        .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addGroup(panel_aggP1Layout.createSequentialGroup()
                                .addComponent(rb_grande1)
                                .addGap(12, 12, 12)
                                .addComponent(rb_mediana1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_small1))
                            .addGroup(panel_aggP1Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_Si1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_No1)))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(panel_aggP1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(btn_modP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_aggP1Layout.setVerticalGroup(
            panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggP1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_id3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_grande1)
                    .addComponent(rb_mediana1)
                    .addComponent(rb_small1))
                .addGap(18, 18, 18)
                .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tf_fabricante3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(tf_duracionB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_años3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(rb_Si1)
                    .addComponent(rb_No1))
                .addGap(18, 18, 18)
                .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_precio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_modelo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(btn_modP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_modificarPLayout = new javax.swing.GroupLayout(jd_modificarP.getContentPane());
        jd_modificarP.getContentPane().setLayout(jd_modificarPLayout);
        jd_modificarPLayout.setHorizontalGroup(
            jd_modificarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_aggP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jd_modificarPLayout.setVerticalGroup(
            jd_modificarPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarPLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_aggP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        popupM_Juegos.add(Modificar);

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        popupM_Juegos.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        panel_aggC.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setText("Identificacion");

        jLabel2.setText("Fabricante");

        jLabel3.setText("Años de uso");

        jLabel4.setText("Precio");

        jLabel5.setText("Modelo");

        jLabel11.setText("Numero de Controles");

        jLabel12.setText("Almacenamiento");

        jLabel13.setText("Tipo de conexion");

        btn_aggC.setText("Agregar");
        btn_aggC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aggCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_aggCLayout = new javax.swing.GroupLayout(panel_aggC);
        panel_aggC.setLayout(panel_aggCLayout);
        panel_aggCLayout.setHorizontalGroup(
            panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggCLayout.createSequentialGroup()
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_aggCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41)
                                .addComponent(tf_modelo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tf_años))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(tf_precio))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                        .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_id, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(tf_fabricante))))
                                .addGap(0, 1, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_tipoC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_numControles, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(panel_aggCLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aggC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        panel_aggCLayout.setVerticalGroup(
            panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggCLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tf_numControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tf_almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tf_tipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btn_aggC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar Consola", panel_aggC);

        panel_aggP.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setText("Identificacion");

        jLabel7.setText("Fabricante");

        jLabel8.setText("Años de uso");

        jLabel9.setText("Precio");

        jLabel10.setText("Modelo");

        jLabel14.setText("Tamaño Pantalla");

        buttonGroup1.add(rb_grande);
        rb_grande.setText("Grande");

        buttonGroup1.add(rb_mediana);
        rb_mediana.setText("Mediana");

        buttonGroup1.add(rb_small);
        rb_small.setText("Pequeña");

        jLabel15.setText("Duracion de Bateria");

        jLabel16.setText("Tiene Estuche");

        rb_Si.setText("Si");

        rb_No.setText("No");

        btn_aggP.setText("Agregar");
        btn_aggP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aggPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_aggPLayout = new javax.swing.GroupLayout(panel_aggP);
        panel_aggP.setLayout(panel_aggPLayout);
        panel_aggPLayout.setHorizontalGroup(
            panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_aggPLayout.createSequentialGroup()
                        .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(41, 41, 41)
                                .addComponent(tf_modelo1))
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(tf_precio1))
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tf_años1))
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_id1)
                                    .addComponent(tf_fabricante1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_duracionB))
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(panel_aggPLayout.createSequentialGroup()
                                        .addComponent(rb_grande)
                                        .addGap(12, 12, 12)
                                        .addComponent(rb_mediana)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_small))
                                    .addGroup(panel_aggPLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_Si)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_No)))
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addContainerGap(123, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_aggPLayout.createSequentialGroup()
                        .addComponent(btn_aggP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(300, 300, 300))))
        );
        panel_aggPLayout.setVerticalGroup(
            panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggPLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_grande)
                    .addComponent(rb_mediana)
                    .addComponent(rb_small))
                .addGap(18, 18, 18)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_fabricante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tf_duracionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_años1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(rb_Si)
                    .addComponent(rb_No))
                .addGap(18, 18, 18)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_modelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_aggP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar Portatil", panel_aggP);

        panel_Listar.setBackground(new java.awt.Color(0, 102, 102));

        tb_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fabricante", "Años de Uso", "Precio", "Modelo", "Tipo de Consola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_lista);

        javax.swing.GroupLayout panel_ListarLayout = new javax.swing.GroupLayout(panel_Listar);
        panel_Listar.setLayout(panel_ListarLayout);
        panel_ListarLayout.setHorizontalGroup(
            panel_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panel_ListarLayout.setVerticalGroup(
            panel_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Listar", panel_Listar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DefaultTableModel actualizarTable(){
        tb_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fabricante", "Años de Uso", "Precio", "Modelo", "Tipo de Consola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel tb = (DefaultTableModel)tb_lista.getModel();
        String tipo = "";
        for (Consola t : consolas) {
            if (t instanceof Portatil) {
                tipo = "Portatil";
            }else if(t instanceof Estacionaria){
                tipo = "Estacionaria";
            }
            Object[] row = {t.getId(),t.getFabricantes(),t.getAñosUso(),t.getPrecio(),t.getModelo(),tipo};
            tb.addRow(row);
        }
        return tb;
    }
    
    private void btn_aggCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aggCMouseClicked
        boolean valido = false;
        String id = tf_id.getText().toUpperCase();
        String fabricante = tf_fabricante.getText();
        int añosUso = Integer.parseInt(tf_años.getText());
        double precio = Double.parseDouble(tf_precio.getText());
        String modelo = tf_modelo.getText();
        int numC = Integer.parseInt(tf_numControles.getText());
        int almacenamiento = Integer.parseInt(tf_almacenamiento.getText());
        String tipoC = tf_tipoC.getText();
        if (id.length() == 8) {
            if (id.substring(0, 4).matches("\\d+")) {
                if (id.substring(4).matches("[A-Z]+")) {
                    valido = true;
                }
            }
        }
        if (valido) {
            consolas.add(new Estacionaria(numC, almacenamiento, tipoC, id, fabricante, añosUso, precio, modelo));
            JOptionPane.showMessageDialog(this, "Creado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Formato no valido");
        }
        tb_lista.setModel(actualizarTable());
        tf_id.setText("");
        tf_años.setText("");
        tf_fabricante.setText("");
        tf_modelo.setText("");
        tf_precio.setText("");
        tf_almacenamiento.setText("");
        tf_numControles.setText("");
        tf_tipoC.setText("");
    }//GEN-LAST:event_btn_aggCMouseClicked

    private void btn_aggPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aggPMouseClicked
        // TODO add your handling code here:
        boolean valido = false;
        String id = tf_id1.getText().toUpperCase();
        String fabricante = tf_fabricante1.getText();
        int añosUso = Integer.parseInt(tf_años1.getText());
        double precio = Double.parseDouble(tf_precio1.getText());
        String modelo = tf_modelo1.getText();
        String sizeP = "";
        int duracionB = Integer.parseInt(tf_duracionB.getText());
        boolean estuche = false;
        if (rb_grande.isSelected()) {
            sizeP = "Grande";
        } else if (rb_mediana.isSelected()) {
            sizeP = "Mediana";
        } else if (rb_small.isSelected()) {
            sizeP = "Pequeña";
        }

        if (rb_Si.isSelected()) {
            estuche = true;
        } else if (rb_No.isSelected()) {
            estuche = false;
        }

        if (id.length() == 8) {
            if (id.substring(0, 4).matches("\\d+")) {
                if (id.substring(4).matches("[A-Z]+")) {
                    valido = true;
                }
            }
        }
        if (valido) {
            consolas.add(new Portatil(sizeP, duracionB, estuche, id, fabricante, añosUso, precio, modelo));
            JOptionPane.showMessageDialog(this, "Creado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Formato incorrecto de ID");
        }
        tb_lista.setModel(actualizarTable());
        tf_id1.setText("");
        tf_años1.setText("");
        tf_fabricante1.setText("");
        tf_modelo1.setText("");
        tf_precio1.setText("");
        tf_duracionB.setText("");
        rb_No.setSelected(false);
        rb_Si.setSelected(false);
        rb_grande.setSelected(false);
        rb_mediana.setSelected(false);
        rb_small.setSelected(false);
    }//GEN-LAST:event_btn_aggPMouseClicked

    private void tb_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listaMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            if (tb_lista.getSelectedRow()>= 0) {
                popupM.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tb_listaMouseClicked

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        // TODO add your handling code here:
        if (consolas.get(tb_lista.getSelectedRow()) instanceof Portatil) {
            jd_modificarP.setModal(true);
            jd_modificarP.pack();
            jd_modificarP.setLocationRelativeTo(this);
            jd_modificarP.setVisible(true);
        }else{
            jd_modificarE.setModal(true);
            jd_modificarE.pack();
            jd_modificarE.setLocationRelativeTo(this);
            jd_modificarE.setVisible(true);
        }
    }//GEN-LAST:event_menuEditarActionPerformed

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(this, "Esta seguro que desea eliminar este objeto?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            consolas.remove(tb_lista.getSelectedRow());
            JOptionPane.showMessageDialog(this, "Eliminado con exito");
            tb_lista.setModel(actualizarTable());
        }
    }//GEN-LAST:event_menuEliminarActionPerformed

    private void menuListarJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarJuegosActionPerformed
        // TODO add your handling code here:
        jd_ListarJuegos.setModal(true);
        jd_ListarJuegos.pack();
        jd_ListarJuegos.setLocationRelativeTo(this);
        jd_ListarJuegos.setVisible(true);
        listaJ.setModel(actualizarLista());
    }//GEN-LAST:event_menuListarJuegosActionPerformed

    private void btn_modCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modCMouseClicked
        // TODO add your handling code here:
        boolean valido = false;
        String id = tf_id2.getText().toUpperCase();
        String fabricante = tf_fabricante2.getText();
        int añosUso = Integer.parseInt(tf_años2.getText());
        double precio = Double.parseDouble(tf_precio2.getText());
        String modelo = tf_modelo2.getText();
        int numC = Integer.parseInt(tf_numControles1.getText());
        int almacenamiento = Integer.parseInt(tf_almacenamiento1.getText());
        String tipoC = tf_tipoC1.getText();
        if (id.length() == 8) {
            if (id.substring(0, 4).matches("\\d+")) {
                if (id.substring(4).matches("[A-Z]+")) {
                    valido = true;
                }
            }
        }
        if (valido) {
            consolas.remove(tb_lista.getSelectedRow());
            consolas.add(tb_lista.getSelectedRow(),new Estacionaria(numC, almacenamiento, tipoC, id, fabricante, añosUso, precio, modelo));
            JOptionPane.showMessageDialog(this, "Modificado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Formato no valido");
        }
        tb_lista.setModel(actualizarTable());
        tf_id2.setText("");
        tf_años2.setText("");
        tf_fabricante2.setText("");
        tf_modelo2.setText("");
        tf_precio2.setText("");
        tf_almacenamiento1.setText("");
        tf_numControles1.setText("");
        tf_tipoC1.setText("");
        jd_modificarE.dispose();
    }//GEN-LAST:event_btn_modCMouseClicked

    private void btn_modPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modPMouseClicked
        // TODO add your handling code here:
        boolean valido = false;
        String id = tf_id3.getText().toUpperCase();
        String fabricante = tf_fabricante3.getText();
        int añosUso = Integer.parseInt(tf_años3.getText());
        double precio = Double.parseDouble(tf_precio3.getText());
        String modelo = tf_modelo3.getText();
        String sizeP = "";
        int duracionB = Integer.parseInt(tf_duracionB1.getText());
        boolean estuche = false;
        if (rb_grande1.isSelected()) {
            sizeP = "Grande";
        } else if (rb_mediana1.isSelected()) {
            sizeP = "Mediana";
        } else if (rb_small1.isSelected()) {
            sizeP = "Pequeña";
        }

        if (rb_Si1.isSelected()) {
            estuche = true;
        } else if (rb_No1.isSelected()) {
            estuche = false;
        }

        if (id.length() == 8) {
            if (id.substring(0, 4).matches("\\d+")) {
                if (id.substring(4).matches("[A-Z]+")) {
                    valido = true;
                }
            }
        }
        if (valido) {
            consolas.remove(tb_lista.getSelectedRow());
            consolas.add(tb_lista.getSelectedRow(),new Portatil(sizeP, duracionB, estuche, id, fabricante, añosUso, precio, modelo));
            JOptionPane.showMessageDialog(this, "Modificado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Formato incorrecto de ID");
        }
        tb_lista.setModel(actualizarTable());
        tf_id3.setText("");
        tf_años3.setText("");
        tf_fabricante3.setText("");
        tf_modelo3.setText("");
        tf_precio3.setText("");
        tf_duracionB1.setText("");
        rb_No1.setSelected(false);
        rb_Si1.setSelected(false);
        rb_grande1.setSelected(false);
        rb_mediana1.setSelected(false);
        rb_small1.setSelected(false);
        jd_modificarP.dispose();
    }//GEN-LAST:event_btn_modPMouseClicked

    private void btn_aggJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aggJMouseClicked
        // TODO add your handling code here:
        String nombre = tf_nombreJ.getText();
        String descripcion = ta_desc.getText();
        Date fechaL = jDateChooser1.getDate();
        double precio = Double.parseDouble(tf_precioJuego.getText());
        String estado = "";
        boolean rentable = false;
        boolean agregado = false;
        int cantD = Integer.parseInt(tf_cantD.getText());
        if (rb_Nuevo.isSelected()) {
            estado = "Nuevo";
        }else if(rb_usado.isSelected()){
            estado = "Usado";
        }
        if (rb_rentableSi.isSelected()) {
            rentable = true;
        }else if(rb_rentableNo.isSelected()){
            rentable = false;
        }
        if (rb_aggSi.isSelected()) {
            agregado = true;
        }else if(rb_aggNo.isSelected()){
            agregado = false;
        }
        consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().add(new Juego(nombre, descripcion, fechaL, precio, estado, rentable, agregado, cantD));
        JOptionPane.showMessageDialog(jd_ListarJuegos, "Agregado exitosamente");
        listaJ.setModel(actualizarLista());
        tf_nombreJ.setText("");
        ta_desc.setText("");
        jDateChooser1.setDate(new Date());
        tf_precioJuego.setText("");
        rb_Nuevo.setSelected(false);
        rb_usado.setSelected(false);
        rb_rentableSi.setSelected(false);
        rb_rentableNo.setSelected(false);
        rb_aggNo.setSelected(false);
        rb_aggSi.setSelected(false);
    }//GEN-LAST:event_btn_aggJMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        if (listaJ.getSelectedIndex() >= 0) {
            if (consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().get(listaJ.getSelectedIndex()).getCantidadDisponible() > 0) {
                int cant = consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().get(listaJ.getSelectedIndex()).getCantidadDisponible();
                consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().get(listaJ.getSelectedIndex()).setCantidadDisponible(cant-1);
            }else{
                consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().remove(listaJ.getSelectedIndex());
            }
            listaJ.setModel(actualizarLista());
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Ingrese nuevo nombre");
        consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().get(listaJ.getSelectedIndex()).setNombre(nombre);
        String descripcion = JOptionPane.showInputDialog("Ingrese nombre: ");
        consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().get(listaJ.getSelectedIndex()).setDesc(descripcion);
        Date fechaL = new Date(JOptionPane.showInputDialog("Ingrese fecha"));
        consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().get(listaJ.getSelectedIndex()).setFechaL(fechaL);
        double precio = Double.parseDouble(JOptionPane.showInputDialog("Ingrese precio"));
        consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().get(listaJ.getSelectedIndex()).setPrecio(precio);
        int cant = Integer.parseInt(JOptionPane.showInputDialog("Ingrese cantidad disponible:"));
        consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles().get(listaJ.getSelectedIndex()).setCantidadDisponible(cant);
        listaJ.setModel(actualizarLista());
    }//GEN-LAST:event_ModificarActionPerformed

    private void listaJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaJMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            if (listaJ.getSelectedIndex() >= 0) {
                popupM_Juegos.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_listaJMouseClicked

    public DefaultListModel actualizarLista(){
        listaJ.setModel(new DefaultListModel());
        DefaultListModel lm = (DefaultListModel) listaJ.getModel();
        for (Juego t : consolas.get(tb_lista.getSelectedRow()).getJuegosDisponibles()) {
            lm.addElement(t);
        }
        return lm;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JButton btn_aggC;
    private javax.swing.JButton btn_aggJ;
    private javax.swing.JButton btn_aggP;
    private javax.swing.JButton btn_modC;
    private javax.swing.JButton btn_modP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JDialog jd_ListarJuegos;
    private javax.swing.JDialog jd_modificarE;
    private javax.swing.JDialog jd_modificarP;
    private javax.swing.JList<String> listaJ;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JMenuItem menuListarJuegos;
    private javax.swing.JPanel panel_Listar;
    private javax.swing.JPanel panel_aggC;
    private javax.swing.JPanel panel_aggC1;
    private javax.swing.JPanel panel_aggP;
    private javax.swing.JPanel panel_aggP1;
    private javax.swing.JPopupMenu popupM;
    private javax.swing.JPopupMenu popupM_Juegos;
    private javax.swing.JRadioButton rb_No;
    private javax.swing.JRadioButton rb_No1;
    private javax.swing.JRadioButton rb_Nuevo;
    private javax.swing.JRadioButton rb_Si;
    private javax.swing.JRadioButton rb_Si1;
    private javax.swing.JRadioButton rb_aggNo;
    private javax.swing.JRadioButton rb_aggSi;
    private javax.swing.JRadioButton rb_grande;
    private javax.swing.JRadioButton rb_grande1;
    private javax.swing.JRadioButton rb_mediana;
    private javax.swing.JRadioButton rb_mediana1;
    private javax.swing.JRadioButton rb_rentableNo;
    private javax.swing.JRadioButton rb_rentableSi;
    private javax.swing.JRadioButton rb_small;
    private javax.swing.JRadioButton rb_small1;
    private javax.swing.JRadioButton rb_usado;
    private javax.swing.JTextArea ta_desc;
    private javax.swing.JTable tb_lista;
    private javax.swing.JTextField tf_almacenamiento;
    private javax.swing.JTextField tf_almacenamiento1;
    private javax.swing.JTextField tf_años;
    private javax.swing.JTextField tf_años1;
    private javax.swing.JTextField tf_años2;
    private javax.swing.JTextField tf_años3;
    private javax.swing.JTextField tf_cantD;
    private javax.swing.JTextField tf_duracionB;
    private javax.swing.JTextField tf_duracionB1;
    private javax.swing.JTextField tf_fabricante;
    private javax.swing.JTextField tf_fabricante1;
    private javax.swing.JTextField tf_fabricante2;
    private javax.swing.JTextField tf_fabricante3;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_id2;
    private javax.swing.JTextField tf_id3;
    private javax.swing.JTextField tf_modelo;
    private javax.swing.JTextField tf_modelo1;
    private javax.swing.JTextField tf_modelo2;
    private javax.swing.JTextField tf_modelo3;
    private javax.swing.JTextField tf_nombreJ;
    private javax.swing.JTextField tf_numControles;
    private javax.swing.JTextField tf_numControles1;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio1;
    private javax.swing.JTextField tf_precio2;
    private javax.swing.JTextField tf_precio3;
    private javax.swing.JTextField tf_precioJuego;
    private javax.swing.JTextField tf_tipoC;
    private javax.swing.JTextField tf_tipoC1;
    // End of variables declaration//GEN-END:variables
}
