/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_fernandopadilla;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wendy
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    ArrayList<Consola> consolas = new ArrayList();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panel_aggC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_fabricante = new javax.swing.JTextField();
        tf_años = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        tf_modelo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_numControles = new javax.swing.JTextField();
        tf_almacenamiento = new javax.swing.JTextField();
        tf_tipoC = new javax.swing.JTextField();
        btn_aggC = new javax.swing.JButton();
        panel_aggP = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_id1 = new javax.swing.JTextField();
        tf_fabricante1 = new javax.swing.JTextField();
        tf_años1 = new javax.swing.JTextField();
        tf_precio1 = new javax.swing.JTextField();
        tf_modelo1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        rb_grande = new javax.swing.JRadioButton();
        rb_mediana = new javax.swing.JRadioButton();
        rb_small = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        tf_duracionB = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        rb_Si = new javax.swing.JRadioButton();
        rb_No = new javax.swing.JRadioButton();
        btn_aggP = new javax.swing.JButton();
        panel_Listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_lista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        panel_aggC.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setText("Identificacion");

        jLabel2.setText("Fabricante");

        jLabel3.setText("Años de uso");

        jLabel4.setText("Precio");

        jLabel5.setText("Modelo");

        jLabel11.setText("Numero de Controles");

        jLabel12.setText("Almacenamiento");

        jLabel13.setText("Tipo de conexion");

        btn_aggC.setText("Agregar");
        btn_aggC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aggCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_aggCLayout = new javax.swing.GroupLayout(panel_aggC);
        panel_aggC.setLayout(panel_aggCLayout);
        panel_aggCLayout.setHorizontalGroup(
            panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggCLayout.createSequentialGroup()
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_aggCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41)
                                .addComponent(tf_modelo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tf_años))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(tf_precio))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_aggCLayout.createSequentialGroup()
                                        .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tf_id, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                            .addComponent(tf_fabricante))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_aggCLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_numControles, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(panel_aggCLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_aggCLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_tipoC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_aggCLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aggC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_aggCLayout.setVerticalGroup(
            panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggCLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(tf_numControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tf_almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_años, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tf_tipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btn_aggC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar Consola", panel_aggC);

        panel_aggP.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setText("Identificacion");

        jLabel7.setText("Fabricante");

        jLabel8.setText("Años de uso");

        jLabel9.setText("Precio");

        jLabel10.setText("Modelo");

        jLabel14.setText("Tamaño Pantalla");

        buttonGroup1.add(rb_grande);
        rb_grande.setText("Grande");

        buttonGroup1.add(rb_mediana);
        rb_mediana.setText("Mediana");

        buttonGroup1.add(rb_small);
        rb_small.setText("Pequeña");

        jLabel15.setText("Duracion de Bateria");

        jLabel16.setText("Tiene Estuche");

        rb_Si.setText("Si");

        rb_No.setText("No");

        btn_aggP.setText("Agregar");
        btn_aggP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aggPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_aggPLayout = new javax.swing.GroupLayout(panel_aggP);
        panel_aggP.setLayout(panel_aggPLayout);
        panel_aggPLayout.setHorizontalGroup(
            panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_aggPLayout.createSequentialGroup()
                        .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(41, 41, 41)
                                .addComponent(tf_modelo1))
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(tf_precio1))
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tf_años1))
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_id1)
                                    .addComponent(tf_fabricante1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))))
                        .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(rb_grande)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(panel_aggPLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(panel_aggPLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rb_Si)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panel_aggPLayout.createSequentialGroup()
                        .addComponent(btn_aggP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panel_aggPLayout.createSequentialGroup()
                            .addComponent(rb_mediana)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rb_small))
                        .addComponent(tf_duracionB))
                    .addComponent(rb_No))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_aggPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(77, 77, 77))
        );
        panel_aggPLayout.setVerticalGroup(
            panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aggPLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_grande)
                    .addComponent(rb_mediana)
                    .addComponent(rb_small))
                .addGap(18, 18, 18)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_fabricante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tf_duracionB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_años1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(rb_Si)
                    .addComponent(rb_No))
                .addGap(18, 18, 18)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_precio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_aggPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_modelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btn_aggP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Agregar Portatil", panel_aggP);

        panel_Listar.setBackground(new java.awt.Color(0, 102, 102));

        tb_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fabricante", "Años de Uso", "Precio", "Modelo", "Tipo de Consola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_lista);

        javax.swing.GroupLayout panel_ListarLayout = new javax.swing.GroupLayout(panel_Listar);
        panel_Listar.setLayout(panel_ListarLayout);
        panel_ListarLayout.setHorizontalGroup(
            panel_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ListarLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        panel_ListarLayout.setVerticalGroup(
            panel_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Listar", panel_Listar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DefaultTableModel actualizarTable(){
        tb_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fabricante", "Años de Uso", "Precio", "Modelo", "Tipo de Consola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel tb = (DefaultTableModel)tb_lista.getModel();
        String tipo = "";
        for (Consola t : consolas) {
            if (t instanceof Portatil) {
                tipo = "Portatil";
            }else if(t instanceof Estacionaria){
                tipo = "Estacionaria";
            }
            Object[] row = {t.getId(),t.getFabricantes(),t.getAñosUso(),t.getPrecio(),t.getModelo(),tipo};
            tb.addRow(row);
        }
        return tb;
    }
    
    private void btn_aggCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aggCMouseClicked
        boolean valido = false;
        String id = tf_id.getText().toUpperCase();
        String fabricante = tf_fabricante.getText();
        int añosUso = Integer.parseInt(tf_años.getText());
        double precio = Double.parseDouble(tf_precio.getText());
        String modelo = tf_modelo.getText();
        int numC = Integer.parseInt(tf_numControles.getText());
        int almacenamiento = Integer.parseInt(tf_almacenamiento.getText());
        String tipoC = tf_tipoC.getText();
        if (id.length() == 8) {
            if (id.substring(0, 4).matches("\\d+")) {
                if (id.substring(4).matches("[A-Z]+")) {
                    valido = true;
                }
            }
        }
        if (valido) {
            consolas.add(new Estacionaria(numC, almacenamiento, tipoC, id, fabricante, añosUso, precio, modelo));
            JOptionPane.showMessageDialog(this, "Creado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Formato no valido");
        }
        tb_lista.setModel(actualizarTable());
        tf_id.setText("");
        tf_años.setText("");
        tf_fabricante.setText("");
        tf_modelo.setText("");
        tf_precio.setText("");
        tf_almacenamiento.setText("");
        tf_numControles.setText("");
        tf_tipoC.setText("");
    }//GEN-LAST:event_btn_aggCMouseClicked

    private void btn_aggPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aggPMouseClicked
        // TODO add your handling code here:
        boolean valido = false;
        String id = tf_id1.getText().toUpperCase();
        String fabricante = tf_fabricante1.getText();
        int añosUso = Integer.parseInt(tf_años1.getText());
        double precio = Double.parseDouble(tf_precio1.getText());
        String modelo = tf_modelo1.getText();
        String sizeP = "";
        int duracionB = Integer.parseInt(tf_duracionB.getText());
        boolean estuche = false;
        if (rb_grande.isSelected()) {
            sizeP = "Grande";
        } else if (rb_mediana.isSelected()) {
            sizeP = "Mediana";
        } else if (rb_small.isSelected()) {
            sizeP = "Pequeña";
        }

        if (rb_Si.isSelected()) {
            estuche = true;
        } else if (rb_No.isSelected()) {
            estuche = false;
        }

        if (id.length() == 8) {
            if (id.substring(0, 4).matches("\\d+")) {
                if (id.substring(4).matches("[A-Z]+")) {
                    valido = true;
                }
            }
        }
        if (valido) {
            consolas.add(new Portatil(sizeP, duracionB, estuche, id, fabricante, añosUso, precio, modelo));
            JOptionPane.showMessageDialog(this, "Creado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Formato incorrecto de ID");
        }
        tb_lista.setModel(actualizarTable());
        tf_id1.setText("");
        tf_años1.setText("");
        tf_fabricante1.setText("");
        tf_modelo1.setText("");
        tf_precio1.setText("");
        tf_duracionB.setText("");
        rb_No.setSelected(false);
        rb_Si.setSelected(false);
        rb_grande.setSelected(false);
        rb_mediana.setSelected(false);
        rb_small.setSelected(false);
    }//GEN-LAST:event_btn_aggPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aggC;
    private javax.swing.JButton btn_aggP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel panel_Listar;
    private javax.swing.JPanel panel_aggC;
    private javax.swing.JPanel panel_aggP;
    private javax.swing.JRadioButton rb_No;
    private javax.swing.JRadioButton rb_Si;
    private javax.swing.JRadioButton rb_grande;
    private javax.swing.JRadioButton rb_mediana;
    private javax.swing.JRadioButton rb_small;
    private javax.swing.JTable tb_lista;
    private javax.swing.JTextField tf_almacenamiento;
    private javax.swing.JTextField tf_años;
    private javax.swing.JTextField tf_años1;
    private javax.swing.JTextField tf_duracionB;
    private javax.swing.JTextField tf_fabricante;
    private javax.swing.JTextField tf_fabricante1;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_id1;
    private javax.swing.JTextField tf_modelo;
    private javax.swing.JTextField tf_modelo1;
    private javax.swing.JTextField tf_numControles;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_precio1;
    private javax.swing.JTextField tf_tipoC;
    // End of variables declaration//GEN-END:variables
}
